AllCops:
  DisplayCopNames: true

Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 200

Style/FrozenStringLiteralComment:
  Enabled: false